### ISSUE TITLE
Keycaps vs Layout

### ISSUE THREAD

**Issue by leo-vwdilab** [victorlucachi/void_ergo#1]
Sorry to open an issue but seemed like the quickest way to get in contact 😉

Interested in building one **void ergo** of my own and was wondering what keycaps did you use (or which ones can someone use) that would not impact with the layout?

Btw: Kudos for the design ⌨️🙏😉

**Comment by victorlucachi** [comment]
Hey, and thanks! No worries, it is quite an effective way to get in touch after all, haha.

The plates are compatible only with Cherry MX style switches, so any compatible keycaps (that use the appropriate stems) should do the trick; all of the keys used in the layout are 1u. I personally used cherry profile, dsa and xda, and I did not encounter any issues.

Good luck with your build, and if you need any help dont hesitate to get in touch.

**Comment by leo-vwdilab** [comment]
Many thanks, will keep you posted 😉

**Comment by fairglen** [comment]
Hi @victorlucachi 
Just dropping by to say thanks for sharing this project of yours 🥇 👍 
This was the [result ](https://github.com/fairglen/qmk_firmware/tree/master/keyboards/handwired/void_ergo)

Do you have a paypal account or something, so that I can donate at least enough for a coffee?
Keep on 🤘

**Comment by victorlucachi** [comment]
> Hi @victorlucachi
> Just dropping by to say thanks for sharing this project of yours 🥇 👍
> This was the [result ](https://github.com/fairglen/qmk_firmware/tree/master/keyboards/handwired/void_ergo)
> 
> Do you have a paypal account or something, so that I can donate at least enough for a coffee?
> Keep on 🤘

Hello!

Thank you for printing it, I love the end result! The orange filament is so vibrant! Hope you find it comfortable enough for daily use. 
Personally I've been going back and forth between a Corne and my Ergo S, and I might be biased here, but I think I like the latter better.

Thanks again, and [a cup of coffee](https://paypal.me/victorlucachi) is much appreciated!
