### ISSUE TITLE
button port question

### ISSUE THREAD

**Issue by UwUham** [victorlucachi/void_ergo#3]
heyo, i was just wondering about this part in particular, cause i feel like it won't print well without supports. Am I supposed to try to insert the button mid print or something to help it stay up?

![image](https://user-images.githubusercontent.com/71855338/137565248-f00bc078-7a34-4d01-92d8-55449341d014.png)

Thanks in advance!

**Comment by UwUham** [comment]
![image](https://user-images.githubusercontent.com/71855338/137575956-6008d614-4660-459e-bb53-527fd11d39f1.png)
do you think that this would be an adequate support beam for the part? sorry, i'm kind of a novice at 3D printing

**Comment by victorlucachi** [comment]
No worries. I'm using Prusaslicer, it's my favorite slicer, and I'd set up something like this:

![image](https://user-images.githubusercontent.com/2669084/137576062-5d2776fb-38f7-4e48-8112-57d77826b5db.png)

a scaled down support enforcer, that would cover the entire shape of the slot. when sliced, it would look like this:

![image](https://user-images.githubusercontent.com/2669084/137576105-323c68a4-02f3-44c4-be50-06e728c62d11.png)

**Comment by patrickmcquay** [comment]
I just printed a set of these, they print surprisingly well, considering the small features. I too use prusaslicer, and the default supports work great.

Be careful getting that support material out though.
