### ISSUE TITLE
Question about the material list info

### ISSUE THREAD

**Issue by renatosuero** [victorlucachi/void_ergo#5]
Hi @victorlucachi ,
first of all, thanks for sharing the amazing keyboard. I'll build that(I've already have the case, if you want some real photos I can send you).
I have some questions about the inserts and screws, can you help me, please?

We have a brass inserts in the list, but it doesn't mention the length, what do you suggest for that?
10 x M2 brass inserts (aliexpress [link](https://www.aliexpress.com/item/4000585933306.html), 3.5mm outer diameter
![Screen Shot 2022-05-20 at 12 53 36](https://user-images.githubusercontent.com/1093214/169565952-20b76950-2677-40df-8b7c-deac07fb68c2.png)
)

another one I'd like to confirm is that one
10 x M2x12 allen head screws (aliexpress [link](https://www.aliexpress.com/item/32966941844.html), 14mm overall length, 4mm diameter head)
I didn't get if I need the 12 or 14mm
![Screen Shot 2022-05-20 at 12 54 33](https://user-images.githubusercontent.com/1093214/169566115-39ea5968-1b89-4689-9fcd-d707cc071b6a.png)

**Comment by renatosuero** [comment]
thank you very much. I'll order the missind components them I'll come back with case and keyboarb 
btw the right side the bottom isn't equal the left one. I didn't realized when I've printed, for me it doesn't affect the usage so I'll go with that one
![image](https://user-images.githubusercontent.com/1093214/169576638-1a2acf15-b477-4a08-9a3e-4ae53fa1edae.png)

**Comment by victorlucachi** [comment]
it's not equal in the sense that it's missing the controller mount and usb port? yes, that was intended, because I didnt want/need a port on my right hand. you can mirror the left half in your slicer of choice if you need easy access to the usb port though.

**Comment by renatosuero** [comment]
yes it makes sense, there's no reason to reset or connect into the promicro. I'll build it soon and spam you with tons of photos  😂

**Comment by renatosuero** [comment]
after long time, I'm back :joy: I'm finishing the keyboard, I'll be back with photos and try to help more in other issues
