### ISSUE TITLE
Question about licence

### ISSUE THREAD

**Issue by EdwardNavarro** [victorlucachi/void_ergo#8]
Hi @victorlucachi ,

First, congratulate you for amazing job with void_ergo 💯 .

I'm interested in design a PCB compatible with your case because actually I prefer PCB over handwired keyboards.

So, my question is how the license you have for this project works for my case. I want make it public in the future for everyone without any restrictions, but first, I want to know and be sure about all legal matters. I don't know how the license works.

Thanks so much for you time and help.

**Comment by victorlucachi** [comment]
Hey @EdwardNavarro!

Thank you, appreciate the kind words.

As far as a PCB for the Ergo goes, from my point of view, there are a couple limitations from the start:
- limited space between pcb edge cut and case itself; hotswap sockets are probably not an option with the current case dimensions
- port (usb/trrs jack) placement will definitely have to get tweaked.

The license; you could basically design and sell a PCB of your own for profit, if you choose to do so, or make the project available for free (you could also use a license that allows people to use, share, adapt your design, but not use it commercially).

Keeping in mind the issues mentioned above regarding the 3d models, you would also have to remix the case based on the available STEP files from this repository; you would have to share the remixed case for free, state any changes that you made to it, and you wouldnt be able to sell prints of it or full builds, for profit.

I'd love to see some of your previous PCB designs; I've tried my hand at it for one of my macropads, a couple of revisions for it, but I'd like to learn more about it.

Thank you!
